apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: laravel-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: laravel
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 60
