- op: replace
  path: /spec/rules/0/host
  value: staging.laravel-starter.com
- op: replace
  path: /spec/rules/1/host
  value: staging.api.laravel-starter.com
- op: replace
  path: /spec/rules/2/host
  value: staging.pma.laravel-starter.com

# - op: replace
#   path: /spec/tls/0/hosts/0
#   value: example.com
